#
# Macro file for the initialization phase of "avion_esferico_glare.cc"
# when runing in interactive mode
#
# Sets some default verbose
#
/control/verbose 2
/vis/verbose confirmations
/run/verbose 2
#/tracking/verbose 2
#
# Use this open statement to create an OpenGL view:
#/vis/open OGL 600x600-0+0
#
# Disable auto refresh and quieten vis messages whilst scene and
# trajectories are established:
/vis/viewer/set/autoRefresh false
/vis/verbose errors
#
/control/execute muon_m.mac
