Centro Volumen Ro
[20, 20, -7]
Centro Volumen Rf
[20, 20, -7]
Radio Volumen r
0.8660254037844386
Submuestreo
0.001
Info
[['Density from function cigar on 2024-01-06 14:14:11', 'ro = [20 20 -7]', 'rf = [20 20 -7]', 'r = 0.8660254037844386', 'Se supone que todas las coordenadas y las distancias están en metros', ['Volumen físico datos (N,L,V):', [64, 64, 32], [0.625, 0.625, 0.4375], [0, 0, -14]]], ['Haz cónico de rayos (M,thetaMin,thetaMax):', 40, 0, 1.0471975511965976]]
#
Segundo submuestreo
0.01
#
Class,Data 
Class 0,/gun/particle e+
Class 0,/gun/energy 1.5051217295757309 MeV
Class 0,/gun/position 0.0 7.0 0.0 m
Class 0,/gun/direction 0.0 -1.0 0.0
Class 0,/run/beamOn 5
Class 1,/gun/particle e+
Class 1,/gun/energy 3.4092229384308834 MeV
Class 1,/gun/position 0.0 7.0 0.0 m
Class 1,/gun/direction 0.0 -1.0 0.0
Class 1,/run/beamOn 19
Class 2,/gun/particle e+
Class 2,/gun/energy 7.722166795904 MeV
Class 2,/gun/position 0.0 7.0 0.0 m
Class 2,/gun/direction 0.0 -1.0 0.0
Class 2,/run/beamOn 40
Class 3,/gun/particle e+
Class 3,/gun/energy 17.491334858613907 MeV
Class 3,/gun/position 0.0 7.0 0.0 m
Class 3,/gun/direction 0.0 -1.0 0.0
Class 3,/run/beamOn 56
Class 4,/gun/particle e+
Class 4,/gun/energy 39.61929380992426 MeV
Class 4,/gun/position 0.0 7.0 0.0 m
Class 4,/gun/direction 0.0 -1.0 0.0
Class 4,/run/beamOn 59
Class 5,/gun/particle e+
Class 5,/gun/energy 89.74091769926191 MeV
Class 5,/gun/position 0.0 7.0 0.0 m
Class 5,/gun/direction 0.0 -1.0 0.0
Class 5,/run/beamOn 36
Class 6,/gun/particle e+
Class 6,/gun/energy 203.27046585288716 MeV
Class 6,/gun/position 0.0 7.0 0.0 m
Class 6,/gun/direction 0.0 -1.0 0.0
Class 6,/run/beamOn 33
Class 7,/gun/particle e+
Class 7,/gun/energy 460.4241114016324 MeV
Class 7,/gun/position 0.0 7.0 0.0 m
Class 7,/gun/direction 0.0 -1.0 0.0
Class 7,/run/beamOn 6
Class 8,/gun/particle e+
Class 8,/gun/energy 1042.898000309631 MeV
Class 8,/gun/position 0.0 7.0 0.0 m
Class 8,/gun/direction 0.0 -1.0 0.0
Class 8,/run/beamOn 5
Class 9,/gun/particle e+
Class 9,/gun/energy 2362.2486575232147 MeV
Class 9,/gun/position 0.0 7.0 0.0 m
Class 9,/gun/direction 0.0 -1.0 0.0
Class 9,/run/beamOn 2
Class 10,/gun/particle e-
Class 10,/gun/energy 0.6203636095287571 MeV
Class 10,/gun/position 0.0 7.0 0.0 m
Class 10,/gun/direction 0.0 -1.0 0.0
Class 10,/run/beamOn 23
Class 11,/gun/particle e-
Class 11,/gun/energy 1.5053325229829213 MeV
Class 11,/gun/position 0.0 7.0 0.0 m
Class 11,/gun/direction 0.0 -1.0 0.0
Class 11,/run/beamOn 44
Class 12,/gun/particle e-
Class 12,/gun/energy 3.6527384423329643 MeV
Class 12,/gun/position 0.0 7.0 0.0 m
Class 12,/gun/direction 0.0 -1.0 0.0
Class 12,/run/beamOn 72
Class 13,/gun/particle e-
Class 13,/gun/energy 8.86348891317246 MeV
Class 13,/gun/position 0.0 7.0 0.0 m
Class 13,/gun/direction 0.0 -1.0 0.0
Class 13,/run/beamOn 89
Class 14,/gun/particle e-
Class 14,/gun/energy 21.507544806234407 MeV
Class 14,/gun/position 0.0 7.0 0.0 m
Class 14,/gun/direction 0.0 -1.0 0.0
Class 14,/run/beamOn 91
Class 15,/gun/particle e-
Class 15,/gun/energy 52.18875863935773 MeV
Class 15,/gun/position 0.0 7.0 0.0 m
Class 15,/gun/direction 0.0 -1.0 0.0
Class 15,/run/beamOn 86
Class 16,/gun/particle e-
Class 16,/gun/energy 126.63772424305841 MeV
Class 16,/gun/position 0.0 7.0 0.0 m
Class 16,/gun/direction 0.0 -1.0 0.0
Class 16,/run/beamOn 29
Class 17,/gun/particle e-
Class 17,/gun/energy 307.2905663896486 MeV
Class 17,/gun/position 0.0 7.0 0.0 m
Class 17,/gun/direction 0.0 -1.0 0.0
Class 17,/run/beamOn 20
Class 18,/gun/particle e-
Class 18,/gun/energy 745.6505773179751 MeV
Class 18,/gun/position 0.0 7.0 0.0 m
Class 18,/gun/direction 0.0 -1.0 0.0
Class 18,/run/beamOn 8
Class 19,/gun/particle e-
Class 19,/gun/energy 1809.3454348013424 MeV
Class 19,/gun/position 0.0 7.0 0.0 m
Class 19,/gun/direction 0.0 -1.0 0.0
Class 19,/run/beamOn 4
Class 20,/gun/particle gamma
Class 20,/gun/energy 0.08912628610831566 MeV
Class 20,/gun/position 0.0 7.0 0.0 m
Class 20,/gun/direction 0.0 -1.0 0.0
Class 20,/run/beamOn 544
Class 21,/gun/particle gamma
Class 21,/gun/energy 0.2818431966551849 MeV
Class 21,/gun/position 0.0 7.0 0.0 m
Class 21,/gun/direction 0.0 -1.0 0.0
Class 21,/run/beamOn 1115
Class 22,/gun/particle gamma
Class 22,/gun/energy 0.8912700278375195 MeV
Class 22,/gun/position 0.0 7.0 0.0 m
Class 22,/gun/direction 0.0 -1.0 0.0
Class 22,/run/beamOn 1349
Class 23,/gun/particle gamma
Class 23,/gun/energy 2.818454629910186 MeV
Class 23,/gun/position 0.0 7.0 0.0 m
Class 23,/gun/direction 0.0 -1.0 0.0
Class 23,/run/beamOn 1366
Class 24,/gun/particle gamma
Class 24,/gun/energy 8.912771946495115 MeV
Class 24,/gun/position 0.0 7.0 0.0 m
Class 24,/gun/direction 0.0 -1.0 0.0
Class 24,/run/beamOn 1289
Class 25,/gun/particle gamma
Class 25,/gun/energy 28.184772934507617 MeV
Class 25,/gun/position 0.0 7.0 0.0 m
Class 25,/gun/direction 0.0 -1.0 0.0
Class 25,/run/beamOn 886
Class 26,/gun/particle gamma
Class 26,/gun/energy 89.12843615191322 MeV
Class 26,/gun/position 0.0 7.0 0.0 m
Class 26,/gun/direction 0.0 -1.0 0.0
Class 26,/run/beamOn 400
Class 27,/gun/particle gamma
Class 27,/gun/energy 281.8499957173578 MeV
Class 27,/gun/position 0.0 7.0 0.0 m
Class 27,/gun/direction 0.0 -1.0 0.0
Class 27,/run/beamOn 152
Class 28,/gun/particle gamma
Class 28,/gun/energy 891.2915284463821 MeV
Class 28,/gun/position 0.0 7.0 0.0 m
Class 28,/gun/direction 0.0 -1.0 0.0
Class 28,/run/beamOn 29
Class 29,/gun/particle gamma
Class 29,/gun/energy 2818.522621078633 MeV
Class 29,/gun/position 0.0 7.0 0.0 m
Class 29,/gun/direction 0.0 -1.0 0.0
Class 29,/run/beamOn 1
Class 30,/gun/particle neutron
Class 30,/gun/energy 331.2313917486405 MeV
Class 30,/gun/position 0.0 7.0 0.0 m
Class 30,/gun/direction 0.0 -1.0 0.0
Class 30,/run/beamOn 165
Class 31,/gun/particle neutron
Class 31,/gun/energy 457.4905840206253 MeV
Class 31,/gun/position 0.0 7.0 0.0 m
Class 31,/gun/direction 0.0 -1.0 0.0
Class 31,/run/beamOn 229
Class 32,/gun/particle neutron
Class 32,/gun/energy 631.8774116263758 MeV
Class 32,/gun/position 0.0 7.0 0.0 m
Class 32,/gun/direction 0.0 -1.0 0.0
Class 32,/run/beamOn 147
Class 33,/gun/particle neutron
Class 33,/gun/energy 872.7372262281302 MeV
Class 33,/gun/position 0.0 7.0 0.0 m
Class 33,/gun/direction 0.0 -1.0 0.0
Class 33,/run/beamOn 72
Class 34,/gun/particle neutron
Class 34,/gun/energy 1205.408283362945 MeV
Class 34,/gun/position 0.0 7.0 0.0 m
Class 34,/gun/direction 0.0 -1.0 0.0
Class 34,/run/beamOn 31
Class 35,/gun/particle neutron
Class 35,/gun/energy 1664.8873062052614 MeV
Class 35,/gun/position 0.0 7.0 0.0 m
Class 35,/gun/direction 0.0 -1.0 0.0
Class 35,/run/beamOn 14
Class 36,/gun/particle neutron
Class 36,/gun/energy 2299.5111122268713 MeV
Class 36,/gun/position 0.0 7.0 0.0 m
Class 36,/gun/direction 0.0 -1.0 0.0
Class 36,/run/beamOn 13
Class 37,/gun/particle neutron
Class 37,/gun/energy 3176.0416068683403 MeV
Class 37,/gun/position 0.0 7.0 0.0 m
Class 37,/gun/direction 0.0 -1.0 0.0
Class 37,/run/beamOn 3
Class 38,/gun/particle neutron
Class 38,/gun/energy 4386.68908139794 MeV
Class 38,/gun/position 0.0 7.0 0.0 m
Class 38,/gun/direction 0.0 -1.0 0.0
Class 38,/run/beamOn 2
Class 39,/gun/particle neutron
Class 39,/gun/energy 6058.812660149618 MeV
Class 39,/gun/position 0.0 7.0 0.0 m
Class 39,/gun/direction 0.0 -1.0 0.0
Class 39,/run/beamOn 4
Class 40,/gun/particle proton
Class 40,/gun/energy 344.964498892721 MeV
Class 40,/gun/position 0.0 7.0 0.0 m
Class 40,/gun/direction 0.0 -1.0 0.0
Class 40,/run/beamOn 24
Class 41,/gun/particle proton
Class 41,/gun/energy 516.1591767268643 MeV
Class 41,/gun/position 0.0 7.0 0.0 m
Class 41,/gun/direction 0.0 -1.0 0.0
Class 41,/run/beamOn 38
Class 42,/gun/particle proton
Class 42,/gun/energy 772.3122135017355 MeV
Class 42,/gun/position 0.0 7.0 0.0 m
Class 42,/gun/direction 0.0 -1.0 0.0
Class 42,/run/beamOn 49
Class 43,/gun/particle proton
Class 43,/gun/energy 1155.5856836767641 MeV
Class 43,/gun/position 0.0 7.0 0.0 m
Class 43,/gun/direction 0.0 -1.0 0.0
Class 43,/run/beamOn 41
Class 44,/gun/particle proton
Class 44,/gun/energy 1729.0653300223846 MeV
Class 44,/gun/position 0.0 7.0 0.0 m
Class 44,/gun/direction 0.0 -1.0 0.0
Class 44,/run/beamOn 31
Class 45,/gun/particle proton
Class 45,/gun/energy 2587.144300691835 MeV
Class 45,/gun/position 0.0 7.0 0.0 m
Class 45,/gun/direction 0.0 -1.0 0.0
Class 45,/run/beamOn 10
Class 46,/gun/particle proton
Class 46,/gun/energy 3871.0599977824963 MeV
Class 46,/gun/position 0.0 7.0 0.0 m
Class 46,/gun/direction 0.0 -1.0 0.0
Class 46,/run/beamOn 10
Class 47,/gun/particle proton
Class 47,/gun/energy 5792.14135926805 MeV
Class 47,/gun/position 0.0 7.0 0.0 m
Class 47,/gun/direction 0.0 -1.0 0.0
Class 47,/run/beamOn 4
Class 48,/gun/particle proton
Class 48,/gun/energy 8666.593011981664 MeV
Class 48,/gun/position 0.0 7.0 0.0 m
Class 48,/gun/direction 0.0 -1.0 0.0
Class 48,/run/beamOn 1
Class 49,/gun/particle proton
Class 49,/gun/energy 12967.54167008471 MeV
Class 49,/gun/position 0.0 7.0 0.0 m
Class 49,/gun/direction 0.0 -1.0 0.0
Class 49,/run/beamOn 2
